Single-Sign-On/src/users/urls.py
from users.views import (UserSignUpView, UserProfileView,
                         ListCreateOrganizationsAPIView, OrganizationProfileGetView,
                         OrganizationUsersAPIView, ListAllUsersAPIView, activate)
from django.urls import path, re_path
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy
app_name = 'users'

urlpatterns = [
    path('signup/', UserSignUpView.as_view(), name='signup-api'),
    path('activate/<str:uidb64>/<str:token>/', activate, name='activate-user'),
    path('password-reset/', auth_views.PasswordResetView.as_view(template_name="users/password_reset.html", email_template_name='users/password_reset_email.html', success_url="done/"), name='reset_password'),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(template_name="users/password_reset_done.html"), name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name="users/password_reset_confirm.html", success_url="password-reset-complete/"), name="password_reset_confirm"),
    path('password-reset-confirm/<uidb64>/set-password/password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(template_name="users/password_reset_complete.html"), name='password_reset_complete'),
    path('user/', UserProfileView.as_view(), name='user-retrieve-update-destroy-api'),
    path('users/all/', ListAllUsersAPIView.as_view(), name='list-all-users-api'),
    path('organizations/', ListCreateOrganizationsAPIView.as_view(), name='list-create-org'),
    path('organizations/users/', OrganizationUsersAPIView.as_view(), name='org-users'),
    path('organization/<int:pk>/detail/', OrganizationProfileGetView.as_view(), name='org-retrieve-api'),
]

Single-Sign-On/src/users/models.py
import uuid

from django.contrib.auth.base_user import AbstractBaseUser
from django.contrib.auth.models import PermissionsMixin
from django.core.exceptions import ValidationError
from django.db import models
from django.utils.translation import ugettext_lazy as _
from rest_framework.exceptions import APIException

from .managers import CustomUserManager
import services.models as services_models

class Organization(models.Model):

    name = models.CharField(max_length=50)
    joining_date = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name


class User(AbstractBaseUser, PermissionsMixin):
    """
    Model to store all kinds of users in the database.
    """
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False,
                          serialize=False, verbose_name='ID')
    email = models.EmailField(_('email address'), unique=True)
    avatar = models.ImageField(upload_to='static', null=True, blank=True)
    first_name = models.CharField(_('first name'), max_length=30)
    last_name = models.CharField(_('last name'), max_length=30, blank=True, null=True)
    nickname = models.CharField(_('nickname'), max_length=30, blank=True, null=True)
    affiliation = models.CharField(_('affiliation'), max_length=64, blank=True, null=True)

    organization = models.ForeignKey(Organization, on_delete=models.SET_NULL,
                                     related_name='users', null=True, blank=True)
    admin_org = models.OneToOneField(Organization, on_delete=models.SET_NULL,
                                     related_name='admin', null=True, blank=True)

    is_active = models.BooleanField(_('is active'), default=True)
    is_staff = models.BooleanField(_('staff'), default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    objects = CustomUserManager()

    EMAIL_FIELD = 'email'
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['first_name', 'last_name']

    class Meta:
        verbose_name = _('user')
        verbose_name_plural = _('users')

    def __str__(self):
        user_representation = self.first_name
        if self.last_name:
            user_representation += f" {self.last_name}"
        return user_representation

    def save(self, force_insert=False, force_update=False, using=None,
             update_fields=None):
        try:
            self.clean()
        except ValidationError as e:
            raise APIException(str(e))
        if self.admin_org:
            if self.organization:
                if self.organization != self.admin_org:
                    raise APIException(str(f'User is a part of {self.organization}'))
            else:
                self.organization = self.admin_org
        created = self._state.adding
        super(User, self).save()
        if created and not self.is_staff:
            for service in services_models.Service.objects.all():
                connection = services_models.Connection(user=self, service=service)
                connection.save()


class OrganizationJoinRequest(models.Model):

    org = models.ForeignKey(Organization, on_delete=models.CASCADE,
                            related_name='join_requests')
    user = models.ForeignKey(User, on_delete=models.CASCADE,
                             related_name='org_requests')

    class Meta:
        unique_together = ['org', 'user']

    def save(self, force_insert=False, force_update=False, using=None,
             update_fields=None):
        if self.user.organization == self.org:
            raise APIException(f'User is already a member of {self.org}')
        super().save(force_insert=False, force_update=False, using=None,
                     update_fields=None)

    def accept(self):
        self.user.organization = self.org
        self.user.save()
        self.delete()

Single-Sign-On/src/users/views.py
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.utils.encoding import force_bytes, force_text
from django.contrib.sites.shortcuts import get_current_site
from django.contrib.auth import get_user_model
from django.core.mail import send_mail
from django.template.loader import render_to_string
from django.conf import settings
from django.http import HttpResponse

from rest_framework import status
from rest_framework.generics import (RetrieveUpdateDestroyAPIView, ListAPIView,
                                     ListCreateAPIView, RetrieveAPIView)
from rest_framework.permissions import (IsAuthenticated, SAFE_METHODS)
from rest_framework.response import Response
from rest_framework.views import APIView

from users.models import Organization
from users.permissions import (IsOwner, IsOrganizationAdminOrSSOAdmin,
                               IsOrganizationAdmin, IsSSOAdminOrReadOnly)
from users.serializers import (CreateUserSerializer, UserSerializer,
                               OrganizationSerializer, PublicOrganizationSerializer,
                               PublicUserSerializer)

from .tokens import account_activation_token

User = get_user_model()


class ListCreateOrganizationsAPIView(ListCreateAPIView):
    permission_classes = (IsAuthenticated, IsSSOAdminOrReadOnly,)

    def get_serializer_class(self):
        if self.request.method in SAFE_METHODS:
            return PublicOrganizationSerializer
        else:
            return OrganizationSerializer

    def get_queryset(self):
        return Organization.objects.all()


class OrganizationUsersAPIView(ListAPIView):

    permission_classes = (IsAuthenticated, IsOrganizationAdmin,)
    serializer_class = PublicUserSerializer

    def get_queryset(self):
        request_user = self.request.user
        return request_user.admin_org.users.exclude(id=request_user.id)


class ListAllUsersAPIView(ListAPIView):
    serializer_class = PublicUserSerializer

    def get_queryset(self):
        request_user = self.request.user
        return User.objects.exclude(id=request_user.id)


class OrganizationProfileGetView(RetrieveAPIView):
    permission_classes = (IsAuthenticated,)
    queryset = Organization.objects.all()

    def retrieve(self, request, *args, **kwargs):
        organization = self.get_object()
        serializer = PublicOrganizationSerializer(organization)
        if IsOrganizationAdminOrSSOAdmin().has_object_permission(request, self, organization):
            serializer = OrganizationSerializer(organization)
        return Response(serializer.data)


class UserProfileView(RetrieveUpdateDestroyAPIView):
    permission_classes = (IsAuthenticated, IsOwner,)
    queryset = User.objects.all()
    serializer_class = UserSerializer

    def get_object(self):
        return self.request.user


class UserSignUpView(APIView):

    def post(self, request, *args, **kwargs):
        serialized = CreateUserSerializer(data=request.data)
        if serialized.is_valid():
            
            serializer_data = serialized.validated_data

            user = User.objects.create_user(**serializer_data)
            user.is_active = False
            user.save()
            
            current_site = get_current_site(request)
            mail_subject = 'Activate your account at %s' % current_site.domain
            
            message = render_to_string('users/email_template.html', {
                        'user': user,
                        'domain': current_site.domain,
                        'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                        'token': account_activation_token.make_token(user),
                    })

            to_email = serializer_data["email"]
            send_mail(mail_subject, message, settings.EMAIL_HOST_USER, [to_email])

            return Response('Please confirm your email address to complete the registration', status=status.HTTP_201_CREATED)

        else:
            return Response(serialized.errors, status=status.HTTP_400_BAD_REQUEST)


def activate(request, uidb64, token):
    try:
        uid = force_text(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except(TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None
    
    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.save()
        return HttpResponse('''
            <h2>Thank you for your email confirmation. Redirecting...<h2> 	
            <script>
                function redirect(){
                window.location.href = "https://tdd.ai";
                }
        
                setTimeout(redirect, 2000);
            </script>
        ''')
    else:
        return HttpResponse('Activation link is invalid!')

Single-Sign-On/src/templates/users/email_template.html
{% autoescape off %}
Hi,

Please click on the link to confirm your registration,
http://{{ domain }}{% url 'users:activate-user' uidb64=uid token=token %}

{% endautoescape %}

Single-Sign-On/src/templates/users/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width">
	<meta name="keywords" content="">
	<meta name="author" content="Elijah Sears">
	
	<title>TDD AUTH</title>
	

	<!-- Stylesheets -->
    <link rel="stylesheet" type="text/css" href="{% static "css/styles.css" %}">
    <link rel="stylesheet" type="text/css" href="{% static "css/bootstrap.min.css" %}">
    <style>@import url(https://fonts.googleapis.com/css?family=Fira+Sans:400,500,600,700,800);</style>
  
  </head>

  <body>
    <div id="root">
      <div class="App">
        {% block content %}

        {% endblock %}
      </div>
    </div>
  </body>

</html>

Single-Sign-On/src/templates/users/password_reset.html
{% extends './index.html' %}
{% load widget_tweaks %}

{% block content %}
    <div class="auth-wrapper">
        <div class="auth-inner">
            <div>                
                <form method="post">
                    <h3>Forgot your password?</h1>
                    <h3>Please enter your email</h3>
                    {% csrf_token %}
                    <div class="form-group">
                        {% for field in form %}
                            <label>{{ field.label }}</label>
                                {{ field|add_class:"form-control"|attr:"placeholder:Enter your email"|attr:"name:email" }}
                                
                            {% if field.errors %}
                                <div class="alert alert-danger">
                                    {{field.errors}}
                                </div>
                            {% endif %}
                        {% endfor %}
                                
                    </div>
                    <button id="button" type="submit" class="btn btn-primary btn-block" disabled="">Send password reset email</button>
                </form>
            </div>
        </div>
    </div>

    <script>
            email = document.querySelector('input[name="email"]')
            email.addEventListener("change", (e)=>{
                if (e.target.value){
                    button.disabled=false
                    button.className = 'btn btn-primary btn-block'
                }
                else {
                    button.disabled=true
                    button.className ='disabled-btn btn btn-primary btn-block'
                }
            }) 
    </script>
{% endblock %}

Single-Sign-On/src/templates/users/password_reset_complete.html
{% extends './index.html' %}

{% block content %}
<div class="auth-wrapper">
    <div class="auth-inner">
        <div> 
            <h3>Your password has been reset. you can <a href="/">Go to home page</a></h1>
        </div>
    </div>
</div>
{% endblock %}

Single-Sign-On/src/templates/users/password_reset_confirm.html
{% extends './index.html' %}
{% load widget_tweaks %}

{% block content %}
    <div class="auth-wrapper">
        <div class="auth-inner">
            <div>                
                <form method="post">
                    <h3>Enter a new Password</h1>
                    {% csrf_token %}
                    <div class="form-group">
                        {% for field in form %}
                            <label>{{ field.label }}</label>
                            {% if forloop.first %}
                                {{ field|add_class:"form-control"|attr:"placeholder:Enter a new password"|attr:"name:password" }}
                            {% else %}   
                                {{ field|add_class:"form-control"|attr:"placeholder:Confirm password"|attr:"name:confirm" }}
                            {% endif %}

                            {% if field.errors %}
                                <div class="alert alert-danger error">
                                    {{field.errors}}
                                </div>
                            {% endif %}
                        {% endfor %}
                    </div>
        
                    <button id="button" type="submit" class="btn btn-primary btn-block">Send password reset email</button>
                </form>
            </div>
        </div>
    </div>

    <script>
            email = document.querySelector('input[name="password"]')
            email.addEventListener("change", (e)=>{
                if (e.target.value){
                    button.disabled=false
                    button.className = 'btn btn-primary btn-block'
                }
                else {
                    button.disabled=true
                    button.className ='disabled-btn btn btn-primary btn-block'
                }
            }) 
    </script>
{% endblock %}

Single-Sign-On/src/templates/users/password_reset_done.html
{% extends './index.html' %}

{% block content %}
<div class="auth-wrapper">
    <div class="auth-inner">
        <div> 
            <h3>We've emailed you instructions for resetting your password</h1>
            <h3>If you don't receive an email, please make sure you've entered the correct email address</h3>     
        </div>
    </div>
</div>
{% endblock %}

Single-Sign-On/src/templates/users/password_reset_email.html
{% autoescape off %}
Hi,

You can create a new password clicking the link below.
http://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}

{% endautoescape %}